#!/bin/bash
#
APACHE2=$(dpkg-query -W -f='${status}' apache2 2>/dev/null | grep -c "Apache on juba olemas")
if [ $APACHE2 -eq 0 ]
then
	echo "Apache2 installeerimine"
	apt-get install apache2 -y

elif [ $APACHE2 -eq 1 ]
then
	echo "Apache2 on juba installitud"
	systemctl status apache2
fi
